"""debug

Revision ID: b18669a02841
Revises: 2589f5d5ac31
Create Date: 2025-05-22 22:26:18.762755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b18669a02841'
down_revision: Union[str, None] = '2589f5d5ac31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'sdfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('sdfs', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
